### ISSUE TITLE
Focus could not be located at the last line of gdb shell in emacs when golden-ration is on

### ISSUE THREAD

**Issue by redguardtoo** [roman/golden-ratio.el#16]
I open gdb shell by typing `M-x gud-gdb`. When I type `run` in gdb shell, the focus is not at the last line of shell. So I need move the focus and type `next`, then focus is moving again (two lines above the last line of shell). This make debugging with gdb very hard. emacs 24.1.50.2, os x 10.7.3

**Comment by roman** [comment]
I guess this is already merged in upstream... closing
