### ISSUE TITLE
Add `handle-select-window` to `golden-ratio-extra-commands`

### ISSUE THREAD

**Issue by ZaneA** [roman/golden-ratio.el#24]
Currently golden-ratio doesn't kick in if you have `mouse-autoselect-window` on and you move your mouse over another window. After some digging it looks like simply adding `handle-select-window` to `golden-ratio-extra-commands` does the trick. Very simple fix but I can open a pull-request if you'd prefer.

Cheers,
Zane

**Comment by roman** [comment]
It seems this one is also merged, closing.
