### ISSUE TITLE
golden ratio with ecb problem

### ISSUE THREAD

**Issue by tejasbubane** [roman/golden-ratio.el#30]
I love Golden ratio and been using it for a while now, but recently I started using Emacs Code browser for my rails projects and the golden-ratio mode is working a bit odd with ecb. It resizes the ecb windows to a larger size.
This behaviour might be natural for the golden ratio, but it takes up unnecessary space on the screen. I want golden-ratio to resize everything except ecb buffers.
Is there any way to do so?

**Comment by roman** [comment]
You can try add the buffer name of ECB in this list:

https://github.com/roman/golden-ratio.el/blob/master/golden-ratio.el#L37

I'm going to close this, please re-open if this doesn't work for you.

Cheers.
