### ISSUE TITLE
Odd behavior with quit-window

### ISSUE THREAD

**Issue by marktran** [roman/golden-ratio.el#39]
1. Create at least 2 windows
2. C-h v
3. Type in `golden-ratio-extra-commands`. Help buffer will open in other window.
4. Move to window with Help buffer.
5. Hit `q` for `quit-window`
6. Another window will be selected but the window that previously had the Help buffer will be resized as the primary window.

**Comment by roman** [comment]
@marktran Can't seem to reproduce, which version of emacs do you have?

**Comment by marktran** [comment]
This problem actually went away—not sure what was causing it. Closing...
