### ISSUE TITLE
Golden ratio not working with Evil? 

### ISSUE THREAD

**Issue by ReneFroger** [roman/golden-ratio.el#41]
For example I have bounded the keys `nn` to `   (evil-window-vsplit)`

But there is no golden ratio. It will only be activated, when I turn on Helm in one of the windows. 

Propably this is a bug, or Golden Ratio conflicts with Evil?

**Comment by thierryvolpiatto** [comment]
ReneFroger <notifications@github.com> writes:

> For example I have bounded the keys nn to (evil-window-vsplit)
>
> But there is no golden ratio. It will only be activated, when I turn on Helm in one of the windows.
>
> Propably this is a bug, or Golden Ratio conflicts with Evil?

It is just that golden-ratio probably doesn't support
evil-window-vsplit, I don't know how this is working, but if it doesn't
use pop-to-buffer, golden-ratio will not run, but as soon as you switch
to other buffer with e.g C-x o the window will be golden-ratio resized.
Did you try adding evil-window-vsplit to golden-ratio-extra-commands ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by ReneFroger** [comment]
@thierryvolpiatto Many thanks for your useful suggestion! 

`golden-ratio-extra-commands` does the trick. 

For future reference: 

`(golden-ratio-mode)

 (setq golden-ratio-extra-commands
        (append golden-ratio-extra-commands
                '(evil-window-left
                  evil-window-right
                  evil-window-up
                  evil-window-down
                  buf-move-left
                  buf-move-right
                  buf-move-up
                  buf-move-down
                  window-number-select
                  select-window
                  select-window-1
                  select-window-2
                  select-window-3
                  select-window-4
                  select-window-5
                  select-window-6
                  select-window-7
                  select-window-8
                  select-window-9)
        )
)
`
