### ISSUE TITLE
Not works with emacs from git

### ISSUE THREAD

**Issue by 11111000000** [roman/golden-ratio.el#50]
no errors but not works

**Comment by thierryvolpiatto** [comment]
Peter <notifications@github.com> writes:

1) golden-ratio is working fine with emacs-25.
2) Your bug report is pretty unuseful, if something is not working,
please elaborate, give a recipe, a backtrace or whatever description of
your problem.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by syl20bnr** [comment]
Seems to me that we can close this issue :-)
@11111000000 if you have anything new to add then feel free to reopen it.
