### ISSUE TITLE
golden-ratio call requires golden-ratio-mode

### ISSUE THREAD

**Issue by eikek** [roman/golden-ratio.el#51]
Since commit e2cbe682 the function `golden-ratio` requires to enable `golden-ratio-mode`. Is this by accident or on purpose? If the latter, the readme is a little misleading, as it states "To call golden ratio manually just `M-x golden-ratio`".

**Comment by thierryvolpiatto** [comment]
Eike Kettner <notifications@github.com> writes:

> Since commit e2cbe68 the function golden-ratio requires to enable
> golden-ratio-mode. Is this by accident or on purpose?

It is an error indeed, should be fixed now.
Thanks.


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by eikek** [comment]
Thierry Volpiatto <notifications@github.com> writes:

> Eike Kettner <notifications@github.com> writes:
>
>> Since commit e2cbe68 the function golden-ratio requires to enable
>> golden-ratio-mode. Is this by accident or on purpose?
>
> It is an error indeed, should be fixed now.
> Thanks.

Confirmed. Thank you!

--
gpg: AD7AC35E
finger print: 137F BB0B 1639 D25F DC5D  E59C B412 C5F5 AD7A C35E
