### ISSUE TITLE
Vertical spilt gives reverse golden ratio

### ISSUE THREAD

**Issue by dakrone** [roman/golden-ratio.el#55]
When I use a horizontal split, everything is peachy (dark modeline is the active window):

![screenshot from 2015-07-20 07-34-16](https://cloud.githubusercontent.com/assets/19060/8776919/d8d30726-2eb1-11e5-8593-d8f160303dcf.png)
![screenshot from 2015-07-20 07-34-20](https://cloud.githubusercontent.com/assets/19060/8776920/d8d43d3a-2eb1-11e5-90bf-0b509ab26c89.png)

But when I split vertically, I get "opposite" golden ratio, where the active window is the smaller one:

![screenshot from 2015-07-20 07-34-36](https://cloud.githubusercontent.com/assets/19060/8776922/dd3a869a-2eb1-11e5-914f-3a87d8bdbd72.png)
![screenshot from 2015-07-20 07-34-38](https://cloud.githubusercontent.com/assets/19060/8776921/dd383e12-2eb1-11e5-9562-efa091159358.png)

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

> When I use a horizontal split, everything is peachy (dark modeline is the active window):
>
> screensh
> screensh
>
> But when I split vertically, I get "opposite" golden ratio, where the active window is the smaller one:
>
> screensh
> screensh

This is not reproductible here, it seems some other mode is confusing
golden-ratio.

Try to start for emacs -Q, and then load only golden-ratio and enable
its mode, it should work fine.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by dakrone** [comment]
Okay, I'll try to reproduce and see what's interfering with it. Thanks!

**Comment by indigoviolet** [comment]
btw, I can repro this on a widescreen monitor, with `(setq golden-ratio-auto-scale t)` -- if I turn that off it goes away

**Comment by DonHugo69** [comment]
I encountered the same issue and the reason seems to be evil mode. A possible solution can be found [here](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bspacemacs/spacemacs-navigation/packages.el). One can add something like 
```el
;; golden-ratio-extra-commands
(dolist (f '(evil-avy-goto-word-or-subword-1
             evil-avy-goto-line
             evil-window-delete
             evil-window-split
             evil-window-vsplit
             evil-window-left
             evil-window-right
             evil-window-up
             evil-window-down
             evil-window-bottom-right
             evil-window-top-left
             evil-window-mru
             evil-window-next
             evil-window-prev
             evil-window-new
             evil-window-vnew
             evil-window-rotate-upwards
             evil-window-rotate-downwards
             evil-window-move-very-top
             evil-window-move-far-left
             evil-window-move-far-right
             evil-window-move-very-bottom))
  (add-to-list 'golden-ratio-extra-commands f))
```
to the golden-ratio config.
