### ISSUE TITLE
Only activate `golden-ratio-mode` when number of windows > 2

### ISSUE THREAD

**Issue by kir0ul** [roman/golden-ratio.el#79]
Hi,
Usually, when I have only two windows open, I would like to have them at the same size.
Is there a way to only activate `golden-ratio-mode` when the number of windows is strictly superior to two, and deactivate it otherwise?
Thanks anyway for this great package :)

**Comment by wictory** [comment]
You can create functions which inhibits `golden-ratio-mode` based on their return value. The config snippet you're looking for is the following:
```elisp
(add-to-list 'golden-ratio-inhibit-functions
             (lambda () (<= (length (window-list)) 2)))
```

**Comment by kir0ul** [comment]
Thanks 👍
