### ISSUE TITLE
golden ratio with org timestamp

### ISSUE THREAD

**Issue by barslmn** [roman/golden-ratio.el#94]
Hi,
I am experiencing this weird behaviour with golden-ratio and orgmode timestamp.

When golden-ratio is enabled, timestamp widget replaces the active buffer.

GNU Emacs 29.1 (build 2, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars) of 2023-08-30, modified by Debian
GNU Emacs     v29.1            nil
Doom core     v3.0.0-pre       HEAD -> master 4d072ce8 2023-12-02 13:57:53 -0500
Doom modules  v23.12.0-pre     HEAD -> master 4d072ce8 2023-12-02 13:57:53 -0500
Org mode version 9.7 (9.7-??-57b94f344 @ /home/bar/.emacs.d/.local/straight/build-29.1/org/)

Golden-ratio version:
❯ git log
commit 375c9f287dfad68829582c1e0a67d0c18119dab9 (grafted, HEAD -> master, replaced, origin/master, origin/HEAD)
Author: Roman Gonzalez <roman@users.noreply.github.com>
Date:   Tue Sep 12 11:25:57 2023 -0700

    Merge pull request #91 from pataquets/use-cl-lib
    
    Switch from 'cl' to 'cl-lib' to supress warnings.

Thanks,
B

https://github.com/roman/golden-ratio.el/assets/43095157/7312615d-0ab6-4ccc-9831-17202c5139f0

**Comment by larrasket** [comment]
Same issue

**Comment by wakenmeng** [comment]
Same here

**Comment by sashkachan** [comment]
You're probably using doom emacs with pop-up mode? https://github.com/doomemacs/doomemacs/issues/2438
This is the related issue to look at.

**Comment by kennethbruskiewicz** [comment]
This occurs with org-capture as well.

**Comment by barslmn** [comment]
> You're probably using doom emacs with pop-up mode? [doomemacs/doomemacs#2438](https://github.com/doomemacs/doomemacs/issues/2438) This is the related issue to look at.

Thanks for the pointer. Following the link I opt in for the zoom.
